defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: gtd_development

test:
  <<: *defaults
  database: gtd_test

# set these environment variables on your prod server
production:
  database: gtd_development